'use strict';
const canvas=document.querySelector('#arena'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s);
const W=2080,H=1440,VW=1200,VH=696;
const weapons={sword:{reach:105,delay:.35},axe:{reach:90,delay:.55},pickaxe:{reach:85,delay:.45},shovel:{reach:95,delay:.4},bow:{reach:650,delay:.45,ranged:true},longbow:{reach:1000,delay:.3,ranged:true},greatsword:{reach:170,delay:.3},battleaxe:{reach:145,delay:.4}};
const starters=['sword','axe','pickaxe','shovel'],names=Object.keys(weapons);
const recipes=[['grip','Long weapon grip',3,'+20 melee reach'],['heal','Forest bandage',4,'Restore one life'],['time','Trail charm',6,'Add 10 seconds'],['bow','Wooden bow',4,'Includes 8 arrows'],['arrows','12 arrows',2,'Ammo for either bow'],['longbow','Longbow',8,'Faster shots; pierces two slimes'],['greatsword','Greatsword',6,'170 reach; faster swings'],['battleaxe','Battleaxe',6,'145 reach; chops in one hit']];
const points=[[320,280],[680,280],[1040,280],[1400,280],[1760,280],[1760,720],[1400,720],[1040,720],[680,720],[320,1160],[1040,1160],[1760,1160]];
const decor=[];for(const y of [140,470,940,1300])for(let x=150;x<2000;x+=180)decor.push({x,y,kind:(x+y)%3?'tree':'rock'});
const assets={};let ready=false,s,reduced=true,last=0;const keys=new Set();
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),title=n=>n[0].toUpperCase()+n.slice(1);
function reset(mode='playing'){keys.clear();s={mode,menu:null,x:320,y:720,cx:0,cy:0,score:0,lives:3,time:45,elapsed:0,shield:0,boost:0,cooldown:0,attackDelay:0,swing:0,aim:0,hit:0,wood:0,arrows:0,grip:false,owned:[...starters],equipped:'sword',facing:1,moving:false,defeated:0,notice:'',noticeTime:0,trees:decor.filter(d=>d.kind==='tree').map(d=>({...d,hp:2})),items:points.map(([x,y])=>({x,y})),enemies:[[700,450,1],[1400,530,-1],[900,950,1],[1600,1100,-1],[500,1060,-1],[1700,350,1]].map(([x,y,dir])=>({x,y,dir})),particles:[],projectiles:[]};camera();renderMenu();hud();}
function camera(){s.cx=clamp(s.x-VW/2,0,W-VW);s.cy=clamp(s.y-VH/2,0,H-VH);}
function tell(text){s.notice=text;s.noticeTime=2;$('#notice').textContent=text;if(s.menu)renderMenu();}
function burst(p){for(let i=0;i<(reduced?5:14);i++)s.particles.push({x:p.x,y:p.y,vx:Math.random()*160-80,vy:Math.random()*160-80,life:.5});}
function kill(e){s.enemies=s.enemies.filter(v=>v!==e);s.defeated++;burst(e);}
function craft(id){if(s.mode!=='playing'||s.menu!=='craft')return false;const r=recipes.find(r=>r[0]===id);if(!r)return false;if(s.owned.includes(id)||(id==='grip'&&s.grip)){tell('Already crafted.');return false;}if(id==='heal'&&s.lives>=3){tell('Your lives are full.');return false;}if(s.wood<r[2]){tell(`Need ${r[2]} wood. Chop trees with your axe.`);return false;}s.wood-=r[2];if(weapons[id]){s.owned.push(id);s.equipped=id;if(id==='bow')s.arrows+=8;}else if(id==='arrows')s.arrows+=12;else if(id==='grip')s.grip=true;else if(id==='heal')s.lives++;else if(id==='time')s.time+=10;tell(`Crafted: ${r[1]}`);hud();return true;}
function equip(name){if(!s.owned.includes(name)){tell('Craft this weapon with Tab first.');return false;}s.equipped=name;s.menu=null;renderMenu();hud();return true;}
function attack(mx,my){if(!ready||s.mode!=='playing'||s.menu||s.attackDelay>0)return;const target={x:mx+s.cx,y:my+s.cy},w=weapons[s.equipped];s.aim=Math.atan2(target.y-s.y,target.x-s.x);if(w.ranged){if(s.arrows<=0){tell('Out of arrows! Tab → 12 arrows for 2 wood.');return;}s.arrows--;s.attackDelay=w.delay;s.swing=.15;const speed=s.equipped==='longbow'?850:650;s.projectiles.push({x:s.x,y:s.y,vx:Math.cos(s.aim)*speed,vy:Math.sin(s.aim)*speed,remaining:w.reach,pierce:s.equipped==='longbow'?2:1});hud();return;}
s.attackDelay=w.delay;s.swing=.22;const candidates=s.trees.filter(t=>target.x>=t.x-48&&target.x<=t.x+48&&target.y>=t.y-134&&target.y<=t.y+10).sort((a,b)=>distance(a,s)-distance(b,s));if(candidates.length){const t=candidates[0],axe=['axe','battleaxe'].includes(s.equipped);if(distance(t,s)>(s.equipped==='battleaxe'?165:125))tell('Move closer to the tree.');else if(!axe)tell('Equip axe (2) to chop trees.');else{t.hp-=s.equipped==='battleaxe'?2:1;burst(t);if(t.hp<=0){s.trees=s.trees.filter(v=>v!==t);s.wood+=4;tell('+4 wood! Tab to craft.');}else tell('One more swing to chop this tree.');}}
for(const e of [...s.enemies]){const angle=Math.atan2(e.y-s.y,e.x-s.x)-s.aim,wrapped=Math.atan2(Math.sin(angle),Math.cos(angle));if(distance(e,s)<=w.reach+(s.grip?20:0)&&(distance(e,s)<40||Math.abs(wrapped)<=Math.PI/3))kill(e);}hud();}
function updateArrows(dt){for(const a of [...s.projectiles]){const speed=Math.hypot(a.vx,a.vy),d=Math.min(speed*dt,a.remaining),dx=a.vx/speed*d,dy=a.vy/speed*d;const hits=[];for(const e of s.enemies){const t=dx*dx+dy*dy?clamp(((e.x-a.x)*dx+(e.y-a.y)*dy)/(dx*dx+dy*dy),0,1):0;if(Math.hypot(e.x-a.x-dx*t,e.y-a.y-dy*t)<=27)hits.push({t,e});}hits.sort((a,b)=>a.t-b.t);for(const hit of hits){kill(hit.e);if(--a.pierce<=0)break;}a.x+=dx;a.y+=dy;a.remaining-=d;if(a.pierce<=0||a.remaining<=0||a.x<0||a.x>W||a.y<0||a.y>H)s.projectiles=s.projectiles.filter(v=>v!==a);}}
function update(dt){if(s.mode!=='playing'||s.menu)return;s.elapsed+=dt;s.time=Math.max(0,s.time-dt);const boosted=s.boost>0;for(const key of ['shield','boost','cooldown','attackDelay','swing','hit','noticeTime'])s[key]=Math.max(0,s[key]-dt);if(!s.noticeTime){s.notice='';$('#notice').textContent='';}const pressed=(...a)=>a.some(k=>keys.has(k));let dx=Number(pressed('d','ArrowRight'))-Number(pressed('a','ArrowLeft')),dy=Number(pressed('s','ArrowDown'))-Number(pressed('w','ArrowUp'));s.moving=!!(dx||dy);if(dx)s.facing=Math.sign(dx);const len=Math.hypot(dx,dy);if(len){s.x=clamp(s.x+dx/len*300*(boosted?2.2:1)*dt,48,W-48);s.y=clamp(s.y+dy/len*300*(boosted?2.2:1)*dt,48,H-48);}for(const e of s.enemies){e.x+=e.dir*135*dt;if(e.x<90||e.x>W-90){e.x=clamp(e.x,90,W-90);e.dir*=-1;}}updateArrows(dt);for(const p of s.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;}s.particles=s.particles.filter(p=>p.life>0);for(const i of [...s.items])if(distance(s,i)<34){s.items=s.items.filter(v=>v!==i);s.score++;burst(i);}if(s.shield<=0&&s.enemies.some(e=>distance(s,e)<39)){s.lives--;s.shield=1.8;s.hit=.65;}if(s.lives<=0||s.time<=0){s.mode='lose';renderMenu();}else if(s.score>=12){s.mode='win';renderMenu();}camera();hud();}
function hud(){for(const [id,text] of Object.entries({score:`${s.score} / 12`,lives:s.lives,time:`${Math.ceil(s.time)}s`,wood:s.wood,ammo:s.arrows,boost:s.cooldown>0?`${s.cooldown.toFixed(1)}s`:'Ready',equipped:`${title(s.equipped)} equipped`}))$('#'+id).textContent=text;$('#pause').textContent=s.mode==='paused'?'Resume':'Pause';$('#effects').textContent='Effects: '+(reduced?'reduced':'full');}
function toggleMenu(menu){if(s.mode!=='playing')return;s.menu=s.menu===menu?null:menu;keys.clear();renderMenu();}
function pause(){if(!['playing','paused'].includes(s.mode))return;s.mode=s.mode==='playing'?'paused':'playing';keys.clear();renderMenu();hud();}
function boost(){if(s.mode==='playing'&&!s.menu&&s.cooldown<=0){s.boost=.32;s.cooldown=2.5;}}
function renderMenu(){const overlay=$('#overlay'),panel=$('#panel');overlay.hidden=s.mode==='playing'&&!s.menu;if(overlay.hidden){canvas.focus({preventScroll:true});return;}let html='';if(s.menu&&s.mode==='playing'){html=`<div class="menuhead"><h1 id="panelTitle">${s.menu==='craft'?'WOODLAND CRAFTING':'YOUR INVENTORY'}</h1><button data-close>Close</button></div><p>Wood: ${s.wood} · Arrows: ${s.arrows} · The forest is paused</p>`;if(s.menu==='craft'){html+='<div class="cards recipes">'+recipes.map(([id,name,cost,desc])=>{const done=s.owned.includes(id)||(id==='grip'&&s.grip);const disabled=done||s.wood<cost||(id==='heal'&&s.lives>=3);return `<button class="card" data-craft="${id}" ${disabled?'disabled':''}><strong>${name} · ${cost} wood</strong><small>${desc}${done?' · Crafted':''}</small></button>`;}).join('')+'</div><p class="menu-note">'+(s.notice||'Equip axe (2) and click a nearby tree twice to gather wood.')+'</p>';}else html+='<div class="cards">'+names.map((name,i)=>`<button class="card ${s.equipped===name?'selected':''}" data-equip="${name}" ${s.owned.includes(name)?'':'disabled'}><img src="assets/${name}.png" alt=""><strong>${i+1} ${title(name)}</strong><small>${s.owned.includes(name)?(weapons[name].ranged?'Range ':'Reach ')+(weapons[name].reach+(!weapons[name].ranged&&s.grip?20:0)):'Craft with Tab'}</small></button>`).join('')+'</div>';}
else{const heading={start:'VERDANT HOLLOW',paused:'TAKE A BREATHER',win:'THE HOLLOW IS RESTORED',lose:'THE FOREST CLAIMS THIS ROUND'}[s.mode];html=`<h1 id="panelTitle">${heading}</h1>`;if(s.mode==='start')html+='<p>Explore the forest. Collect 12 crystals in 45 seconds.<br>Fight slimes, chop trees, and craft your own weapons.</p><p>WASD / arrows to move · Click to attack · Space to boost<br>2 equips the axe · Tab opens crafting · I opens inventory</p><button class="primary" data-start>Enter the forest</button>';else if(s.mode==='paused')html+='<p>Movement and the timer are paused.</p><button class="primary" data-resume>Continue</button>';else html+=`<p>${s.mode==='win'?`${s.score} crystals recovered with ${Math.ceil(s.time)} seconds left.`:(s.lives<=0?'No lives left.':'Time ran out.')+` You recovered ${s.score} crystals.`}</p><button class="primary" data-start>Play again</button>`;}
panel.innerHTML=html;panel.querySelectorAll('[data-craft]').forEach(b=>b.onclick=()=>craft(b.dataset.craft));panel.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>equip(b.dataset.equip));panel.querySelector('[data-close]')?.addEventListener('click',()=>{s.menu=null;renderMenu();});panel.querySelector('[data-start]')?.addEventListener('click',()=>{if(ready)reset();});panel.querySelector('[data-resume]')?.addEventListener('click',pause);}
// All environment and sprite assets are local; the game uses no remote service.
const world=document.createElement('canvas');world.width=W;world.height=H;const wc=world.getContext('2d');let seed=24;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
for(let y=0;y<H;y+=32)for(let x=0;x<W;x+=32){wc.fillStyle=['#426f4d','#477652','#497954','#3e6b4c'][Math.floor(rand()*4)];wc.fillRect(x,y,32,32);if(rand()<.4){wc.fillStyle='#6d965b';wc.fillRect(x+9,y+15,2,6);}}
for(const y of [280,720,1160]){wc.fillStyle='#9c825c';wc.fillRect(70,y-38,W-140,76);wc.fillStyle='#b39a6c';wc.fillRect(70,y-25,W-140,50);}for(const x of [320,1040,1760]){wc.fillStyle='#a58a60';wc.fillRect(x-32,80,64,H-160);}wc.strokeStyle='#304b40';wc.lineWidth=28;wc.strokeRect(0,0,W,H);wc.strokeStyle='#8caa68';wc.lineWidth=4;wc.strokeRect(23,23,W-46,H-46);
function draw(){ctx.imageSmoothingEnabled=false;ctx.drawImage(world,s.cx,s.cy,VW,VH,0,0,VW,VH);const scene=[...decor.filter(d=>d.kind==='rock'),...s.trees,...s.items.map(d=>({...d,kind:'crystal'})),...s.enemies.map(d=>({...d,kind:'slime'})),{x:s.x,y:s.y,kind:'player'}].sort((a,b)=>a.y-b.y);for(const d of scene){const x=d.x-s.cx,y=d.y-s.cy;if(x<-100||x>VW+100||y<-100||y>VH+160)continue;ctx.fillStyle='#355443';ctx.beginPath();ctx.ellipse(x,y,20,7,0,0,Math.PI*2);ctx.fill();let w=48,h=64,bob=0;if(d.kind==='tree'){w=96;h=144;}if(d.kind==='slime')h+=Math.sin(s.elapsed*6+d.y)*(reduced?1:3);if(d.kind==='crystal'&&!reduced)bob=Math.sin(s.elapsed*3+d.y)*3;if(d.kind==='player'&&s.moving)bob=Math.sin(s.elapsed*14)*(reduced?1:2);if(d.kind==='player'&&s.shield>0){ctx.strokeStyle='#d9eee0';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x,y-28,30,39,0,0,Math.PI*2);ctx.stroke();}if(assets[d.kind]){ctx.save();if(d.kind==='player'&&s.facing<0){ctx.translate(x,y);ctx.scale(-1,1);ctx.drawImage(assets.player,-w/2,-h+10+bob,w,h);}else ctx.drawImage(assets[d.kind],x-w/2,y-h+10+bob,w,h);ctx.restore();}}
const px=s.x-s.cx,py=s.y-s.cy,w=weapons[s.equipped];if(s.swing>0&&!w.ranged){ctx.fillStyle='#eee6b0';for(let i=0;i<=12;i++){const a=s.aim-Math.PI/3+i*Math.PI/18;ctx.fillRect(px+Math.cos(a)*(w.reach+(s.grip?20:0)),py+Math.sin(a)*(w.reach+(s.grip?20:0)),3,3);}}if(assets[s.equipped]){ctx.save();ctx.translate(px+14*s.facing,py-22);if(s.swing>0)ctx.rotate(s.aim+Math.PI/4);ctx.drawImage(assets[s.equipped],-24,-32,48,64);ctx.restore();}for(const a of s.projectiles){ctx.save();ctx.translate(a.x-s.cx,a.y-s.cy);ctx.rotate(Math.atan2(a.vy,a.vx));ctx.drawImage(assets.arrow,-24,-32,48,64);ctx.restore();}ctx.fillStyle='#cfffe3';for(const p of s.particles)ctx.fillRect(p.x-s.cx,p.y-s.cy,4,4);if(s.hit>0){ctx.strokeStyle='#e4ad79';ctx.lineWidth=4;ctx.strokeRect(5,5,VW-10,VH-10);}ctx.fillStyle='#203b36';ctx.fillRect(970,18,212,147);const dot=(p,color,r)=>{ctx.fillStyle=color;ctx.beginPath();ctx.arc(978+p.x/W*196,26+p.y/H*131,r,0,Math.PI*2);ctx.fill();};for(const i of s.items)dot(i,'#9ae9d1',3);for(const e of s.enemies)dot(e,'#e5a37c',3);dot(s,'white',4);}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();attack((e.clientX-r.left)/r.width*VW,(e.clientY-r.top)/r.height*VH);});
window.addEventListener('keydown',e=>{const key=e.key.length===1?e.key.toLowerCase():e.key;if(['Tab',' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(key))e.preventDefault();if(e.repeat)return;keys.add(key);if(key==='Enter'&&['start','win','lose'].includes(s.mode)){if(ready)reset();}else if(key==='r')reset();else if(key==='Tab')toggleMenu('craft');else if(key==='i')toggleMenu('inventory');else if(key==='Escape'){if(s.menu){s.menu=null;renderMenu();}else pause();}else if(key==='p')pause();else if(key===' ')boost();else if(key==='f'){reduced=!reduced;hud();}else if(/^[1-8]$/.test(key)&&s.mode==='playing')equip(names[Number(key)-1]);});
window.addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener('blur',()=>{keys.clear();if(s.mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&s.mode==='playing')pause();});
$('#effects').onclick=()=>{reduced=!reduced;hud();};$('#pause').onclick=pause;$('#restart').onclick=()=>reset();$('#inventory').onclick=()=>toggleMenu('inventory');$('#crafting').onclick=()=>toggleMenu('craft');$('#touchBoost').onclick=boost;
for(const b of document.querySelectorAll('[data-move]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.move);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>keys.delete(b.dataset.move);}
reset('start');Promise.all([...names,'player','tree','rock','slime','crystal','arrow'].map(name=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{assets[name]=im;resolve();};im.onerror=reject;im.src=`assets/${name}.png`;}))).then(()=>{ready=true;}).catch(()=>tell('Artwork could not load. Please reload the page.'));
function frame(t){const dt=Math.min((t-last)/1000,.05);last=t;if(ready){update(dt);draw();}requestAnimationFrame(frame);}requestAnimationFrame(frame);
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});for(const tool of [{name:'read_game_state',description:'Read the current round, resources, and equipped weapon.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode:s.mode,score:s.score,lives:s.lives,seconds:s.time,wood:s.wood,arrows:s.arrows,equipped:s.equipped})},{name:'set_game_pause',description:'Pause or resume the current playable round.',inputSchema:{type:'object',properties:{paused:{type:'boolean'}},required:['paused'],additionalProperties:false},execute:input=>{if(typeof input?.paused!=='boolean')throw Error('paused must be a boolean');if(!['playing','paused'].includes(s.mode))throw Error('Start a round first');if((s.mode==='paused')!==input.paused)pause();return {mode:s.mode};}}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}}
